// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadProjectionDelta } from "./ThreadProjectionDelta";

export type ThreadProjectionDeltaNotification = { threadId: string, subscriptionId: string, delta: ThreadProjectionDelta, };
