// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentMessageDeltaNotification } from "./AgentMessageDeltaNotification";
import type { ReasoningSummaryPartAddedNotification } from "./ReasoningSummaryPartAddedNotification";
import type { ReasoningSummaryTextDeltaNotification } from "./ReasoningSummaryTextDeltaNotification";
import type { ReasoningTextDeltaNotification } from "./ReasoningTextDeltaNotification";

export type ThreadProjectionDelta = { "type": "agentMessage", notification: AgentMessageDeltaNotification, } | { "type": "reasoningSummaryText", notification: ReasoningSummaryTextDeltaNotification, } | { "type": "reasoningSummaryPartAdded", notification: ReasoningSummaryPartAddedNotification, } | { "type": "reasoningText", notification: ReasoningTextDeltaNotification, };
