// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadProjectionEvent } from "./ThreadProjectionEvent";

export type ThreadProjectionEventNotification = { threadId: string, subscriptionId: string, commitId: string, parentCommitId: string | null, event: ThreadProjectionEvent, };
