// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadGoalStatus } from "./ThreadGoalStatus";

/**
 * Authoritative goal state read when publishing a completed turn.
 */
export type ThreadGoalStatusSnapshot = { "type": "known", status: ThreadGoalStatus | null, } | { "type": "unavailable" };
