// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemCompletedNotification } from "./ItemCompletedNotification";
import type { ItemStartedNotification } from "./ItemStartedNotification";
import type { ThreadGoalClearedNotification } from "./ThreadGoalClearedNotification";
import type { ThreadGoalUpdatedNotification } from "./ThreadGoalUpdatedNotification";
import type { ThreadTokenUsageUpdatedNotification } from "./ThreadTokenUsageUpdatedNotification";
import type { TurnCompletedNotification } from "./TurnCompletedNotification";
import type { TurnStartedNotification } from "./TurnStartedNotification";

export type ThreadProjectionEvent = { "type": "turnStarted", notification: TurnStartedNotification, } | { "type": "turnCompleted", notification: TurnCompletedNotification, } | { "type": "itemStarted", notification: ItemStartedNotification, } | { "type": "itemCompleted", notification: ItemCompletedNotification, } | { "type": "tokenUsageUpdated", notification: ThreadTokenUsageUpdatedNotification, } | { "type": "goalUpdated", notification: ThreadGoalUpdatedNotification, } | { "type": "goalCleared", notification: ThreadGoalClearedNotification, };
