packages:
  - .

allowBuilds:
  esbuild: true

blockExoticSubdeps: true

minimumReleaseAge: 10080
minimumReleaseAgeExclude: []
patchedDependencies:
  "@heroui/react@3.2.2": patches/@heroui__react@3.2.2.patch

recursiveInstall: false
strictDepBuilds: true
trustPolicy: no-downgrade
trustPolicyExclude: []
trustPolicyIgnoreAfter: 10080
