import type {
  AllowedBoundaryDirection,
  BoundaryAudience,
  BoundaryConsumer,
  BoundaryPolicy,
  PublicBoundaryModule,
} from "./contracts";

// These helpers only expand the explicit declarations below. They never discover
// files, exports, or consumers; adding an import cannot grant itself permission.
function publicModule(
  owner: string,
  file: string,
  exports: readonly string[],
  purpose: string,
  audience: BoundaryAudience = "production",
): PublicBoundaryModule {
  return { path: `src/features/${owner}/${file}`, owner, exports, purpose, audience };
}

function directions(
  consumer: BoundaryConsumer,
  targets: readonly string[],
  audience: BoundaryAudience = "production",
): AllowedBoundaryDirection[] {
  return targets.map((target) => ({ consumer, target, audience }));
}

export const boundaryPolicy: BoundaryPolicy = {
  features: [
    "activeThreadSession",
    "appShell",
    "browserLaunch",
    "committedTranscriptSurface",
    "composerEditor",
    "composerInputQueue",
    "composerTurnControl",
    "currentTask",
    "documentTitle",
    "guiHost",
    "projection",
    "projectionIngress",
    "qrAccess",
    "skillCatalog",
    "threadHistory",
    "threadRuntime",
    "transcriptState",
  ],
  publicModules: [
    publicModule(
      "activeThreadSession",
      "activeThreadSession.ts",
      [
        "ActiveThreadActivationFailure",
        "ActiveThreadActivationOutcome",
        "ActiveThreadActivationWarning",
        "ActiveThreadCompactionRole",
        "ActiveThreadComposerRole",
        "ActiveThreadSession",
        "ActiveThreadSessionController",
        "ActiveThreadSessionSnapshot",
        "ActiveThreadSkillsRole",
        "CreateActiveThreadSessionInput",
        "createActiveThreadSession",
      ],
      "Application session construction, connection lifecycle, activation results, and consumer roles.",
    ),
    publicModule(
      "activeThreadSession",
      "activeThreadSessionContracts.ts",
      ["ActiveThreadCompactionView", "ActiveThreadPendingInputEditReservation"],
      "Session-owned compaction presentation and revision-aware pending-input edit reservation.",
    ),
    publicModule(
      "activeThreadSession",
      "activeThreadProjectionFacts.ts",
      ["ActiveThreadProjectionAcceptedEvent", "ActiveThreadProjectionReadModelFact"],
      "Session-owned accepted projection facts consumed by the input queue and read models; replay classification stays private to the session.",
    ),
    publicModule(
      "activeThreadSession",
      "activeThreadSessionReadModel.ts",
      ["activeThreadReadModelTransitionApplied", "buildActiveThreadCandidateReadModelTransition"],
      "Atomic session-revision read-model transition action and baseline transition construction.",
    ),
    publicModule(
      "activeThreadSession",
      "__tests__/activeThreadSessionHarness.ts",
      [
        "ActiveThreadSessionHarness",
        "ActiveThreadSessionHarnessOptions",
        "createActiveThreadSessionHarness",
      ],
      "Controlled real session harness for consumer lifecycle and routing regression tests.",
      "testing",
    ),
    publicModule(
      "appShell",
      "AppCapabilities.ts",
      [
        "AppCapabilities",
        "useActiveThreadId",
        "useActiveThreadSession",
        "useActiveThreadSessionPhase",
        "useActiveThreadSessionSnapshot",
        "useAppCapabilities",
      ],
      "Application capability contract and subscribed session views for routed pages.",
    ),
    publicModule(
      "appShell",
      "AppCapabilitiesContext.tsx",
      ["AppCapabilitiesProvider"],
      "Provider used by the application composition root and page integration harnesses.",
    ),
    publicModule(
      "appShell",
      "AppShell.tsx",
      ["AppShell"],
      "Complete shell layout for application and page assembly.",
    ),
    publicModule(
      "appShell",
      "GuiHostConnectionBridge.tsx",
      ["GuiHostConnectionBridge"],
      "Application-owned bridge between host connection lifecycle and the active session.",
    ),
    publicModule(
      "appShell",
      "useCommittedTranscriptStickyBottom.ts",
      ["useCommittedTranscriptStickyBottom"],
      "Current-task viewport subscription to committed transcript scroll signals.",
    ),
    publicModule(
      "browserLaunch",
      "browserAuthorizationSession.ts",
      ["BrowserAuthorizationSession", "consumeBrowserAuthorizationSession"],
      "Browser launch authorization handoff to host connection and session creation.",
    ),
    publicModule(
      "browserLaunch",
      "guiRouteTarget.ts",
      [
        "CURRENT_TASK_ROUTE_PATH",
        "GuiRouteTarget",
        "HISTORY_DETAIL_ROUTE_PATH",
        "HISTORY_LIST_ROUTE_PATH",
        "isValidThreadId",
        "selectGuiRouteTarget",
        "validateEmptyRouteSearch",
      ],
      "Canonical GUI route destinations, thread-id validation, and route search validation.",
    ),
    publicModule(
      "committedTranscriptSurface",
      "CommittedTranscriptSurface.tsx",
      ["CommittedTranscriptSurface", "ReadOnlyCommittedTranscriptSurface"],
      "Complete live and read-only transcript surfaces without exposing renderer assembly.",
    ),
    publicModule(
      "composerEditor",
      "ComposerEditor.tsx",
      [
        "ComposerEditor",
        "ComposerEditorController",
        "ComposerEditorProps",
        "ComposerEditorSnapshot",
        "ComposerEditorSubmitIntent",
      ],
      "Editor component, controller, and submission contract for turn-control composition.",
    ),
    publicModule(
      "composerEditor",
      "composerDraft.ts",
      [
        "ComposerDraft",
        "ComposerDraftCapture",
        "ComposerDraftRestoreResult",
        "captureComposerDraft",
      ],
      "Opaque editor-owned draft capture and restoration result; queue retains the authoritative capture.",
    ),
    publicModule(
      "composerEditor",
      "SkillNode.ts",
      ["$createSkillNode", "SkillNode", "SkillNodeState"],
      "Authoritative Lexical skill-node construction for real editor-state captures in queue fixtures; serialization and node predicates stay private.",
    ),
    publicModule(
      "composerEditor",
      "__tests__/composerEditorCompositionBrowserTestSupport.ts",
      ["dispatchCompositionEnd"],
      "Browser composition-end event driver for turn-control input regression.",
      "testing",
    ),
    publicModule(
      "composerInputQueue",
      "composerInputPayload.ts",
      ["ReadonlyComposerInputPayload"],
      "Readonly queued user-input payload consumed by editor capture; draft/input ownership remains tracked below.",
    ),
    publicModule(
      "composerInputQueue",
      "composerInputPreview.ts",
      ["ComposerInputPreview"],
      "Queue-owned input preview model rendered by the pending-input UI.",
    ),
    publicModule(
      "composerInputQueue",
      "composerInputQueueContracts.ts",
      [
        "ComposerPendingInputCursor",
        "ComposerPendingInputDetailResult",
        "ComposerPendingInputDisplayKey",
        "ComposerPendingInputEditRestore",
        "ComposerPendingInputLane",
        "ComposerPendingInputMoveDestination",
        "ComposerPendingInputOwnerGoneResult",
        "ComposerPendingInputPageItem",
        "ComposerPendingInputPageRequest",
        "ComposerPendingInputPageResult",
      ],
      "Pending-input pagination, identity, movement, and editor restoration contracts for management consumers.",
    ),
    publicModule(
      "composerInputQueue",
      "composerInputQueueCoordinator.ts",
      [
        "ComposerInputQueueCoordinator",
        "ComposerInputQueueCoordinatorReleaseBlocker",
        "ComposerInputQueueCoordinatorReleaseReservation",
        "ComposerInputQueueCoordinatorReserveReleaseResult",
        "ComposerInputQueueCoordinatorSnapshot",
        "ComposerPendingInputCoordinatorEditReservation",
        "createComposerInputQueueCoordinator",
      ],
      "Queue lifecycle owner, submission/management capability, snapshots, and release reservations used by sessions and turn control.",
    ),
    publicModule(
      "composerInputQueue",
      "composerPendingInputLiveManagement.ts",
      ["ComposerPendingInputCoordinatorEditReservation"],
      "Authoritative save/cancel reservation contract re-exported by the coordinator and consumed by turn-control edit lifecycle tests; live-management implementation stays private.",
    ),
    publicModule(
      "composerInputQueue",
      "__tests__/composerInputQueueTestFixtures.ts",
      ["composerCapture", "composerDraftCapture"],
      "Legal opaque draft/input captures for session and application queue tests.",
      "testing",
    ),
    publicModule(
      "composerTurnControl",
      "ComposerTurnControl.tsx",
      ["ComposerTurnControl"],
      "Complete current-task composer and turn-operation surface.",
    ),
    publicModule(
      "composerTurnControl",
      "composerTurnControlModel.ts",
      ["invalidSelectedSkillPaths"],
      "Consumer-owned catalog validity calculation used to verify editor token presentation against actual turn-control inputs; other control-state helpers stay private.",
    ),
    publicModule(
      "currentTask",
      "CurrentTaskPage.tsx",
      ["CurrentTaskPage"],
      "Routed current-task page and its application integration entry.",
    ),
    publicModule(
      "documentTitle",
      "DocumentTitleOwner.tsx",
      ["DocumentTitleOwner", "HistoryDetailDocumentTitleFactPublisher"],
      "Router-mounted document title owner and history detail title-fact publication.",
    ),
    publicModule(
      "documentTitle",
      "documentTitle.ts",
      ["formatTaskDocumentTitle"],
      "Canonical task-title formatting for history detail presentation.",
    ),
    publicModule(
      "guiHost",
      "appServerProtocol.ts",
      ["ProtocolValidator", "RequestParams", "RequestResponse"],
      "Validator signature and mechanically derived app-server request types for generated protocol artifacts and history requests.",
    ),
    publicModule(
      "guiHost",
      "guiHostClient.ts",
      [
        "GuiHostCommands",
        "GuiHostStatus",
        "StartGuiHostConnectionOptions",
        "startGuiHostConnection",
      ],
      "Host connection entrypoint, command capabilities, and connection status contract.",
    ),
    publicModule(
      "guiHost",
      "guiHostCommandGateway.ts",
      ["GuiHostCommands", "GuiHostCommandError", "isGuiHostCommandError"],
      "Authoritative protocol-linked command capability re-exported by guiHostClient, and command-failure identity for session and queue delivery outcome handling.",
    ),
    publicModule(
      "projection",
      "__tests__/projectionFixtures.ts",
      [
        "attachBaseline",
        "attachReplacement",
        "closedBackpressure",
        "eventAgentMessageDelta",
        "eventItemCompleted",
        "eventItemStarted",
        "eventReasoningItemStarted",
        "eventReasoningSummaryPartAddedDelta",
        "eventReasoningSummaryTextDelta",
        "eventReasoningTextDelta",
        "eventSubscriptionReplacement",
        "eventTokenUsageUpdated",
        "eventTurnCompleted",
        "eventTurnStarted",
      ],
      "Authoritative legal projection baseline and event fixtures for consumer regression tests.",
      "testing",
    ),
    publicModule(
      "projection",
      "__tests__/projectionTestBuilders.ts",
      [
        "agentMessage",
        "agentMessageDelta",
        "attachWithHeadCommitId",
        "attachWithThreadId",
        "attachWithTurns",
        "audioInput",
        "baseTurn",
        "closedWithEnvelope",
        "collabAgentState",
        "collabAgentToolCall",
        "contextCompaction",
        "contextCompactionCompleted",
        "deltaForThreadOwner",
        "deltaWithEnvelope",
        "eventForThreadOwner",
        "eventWithEnvelope",
        "failedTurn",
        "imageInput",
        "inProgressTurn",
        "itemCompleted",
        "itemStarted",
        "localAudioInput",
        "planItem",
        "reasoningItem",
        "reasoningSummaryPartAddedDelta",
        "reasoningSummaryTextDelta",
        "reasoningTextDelta",
        "sleepItem",
        "subAgentActivity",
        "textInput",
        "tokenUsageUpdated",
        "turnCompleted",
        "turnStarted",
        "turnWithStatus",
        "userMessage",
      ],
      "Protocol-linked builders for legal turns, user inputs, items, and projection envelopes; consumers do not duplicate payload definitions.",
      "testing",
    ),
    publicModule(
      "projectionIngress",
      "projectionIngressAdapter.ts",
      ["ProjectionIgnoredReason", "ProjectionIngressAdapter", "ProjectionManualReconnectReason"],
      "Projection admission capability and rejection/reconnect facts used by session and transcript state.",
    ),
    publicModule(
      "qrAccess",
      "QrAccessPopover.tsx",
      ["QrAccessPopover"],
      "Complete QR access action for task and history continuation UI.",
    ),
    publicModule(
      "skillCatalog",
      "skillCatalogOwner.ts",
      ["SkillCatalogCandidate", "SkillCatalogOwner", "SkillCatalogState"],
      "Skill catalog lifecycle and catalog presentation state for session, editor, and turn control.",
    ),
    publicModule(
      "threadHistory",
      "ThreadHistoryDetailPage.tsx",
      ["ThreadHistoryDetailPage"],
      "Routed history detail page.",
    ),
    publicModule(
      "threadHistory",
      "ThreadHistoryListPage.tsx",
      ["ThreadHistoryListPage"],
      "Routed history list page.",
    ),
    publicModule(
      "threadRuntime",
      "threadRuntimeSlice.ts",
      [
        "default",
        "selectThreadRuntimeRecord",
        "selectThreadRuntimeThreadId",
        "selectThreadRuntimeTokenUsage",
      ],
      "Store-mounted runtime read model and selectors consuming session-owned projection facts.",
    ),
    publicModule(
      "transcriptState",
      "transcriptStateImplementation.ts",
      ["buildTranscriptStateFromTurns"],
      "Complete authoritative turns-to-transcript projection for read-only history; incremental mutation helpers stay private.",
    ),
    publicModule(
      "transcriptState",
      "transcriptStateModel.ts",
      [
        "TARGET_TRANSCRIPT_CHUNK_ENTRY_LIMIT",
        "TranscriptEntryId",
        "TranscriptEntryView",
        "TranscriptMessageRendering",
        "TranscriptState",
        "TranscriptTurn",
        "transcriptEntryIdFor",
      ],
      "Authoritative view, turn, state, entry-identity, and chunk-limit contracts re-exported by the slice for transcript rendering and history projection; storage mutation helpers stay private.",
    ),
    publicModule(
      "transcriptState",
      "transcriptStateSelectors.ts",
      [
        "selectLastTranscriptFragmentIdsByTurnIdFromTranscriptState",
        "selectTranscriptChunkFromTranscriptState",
        "selectTranscriptContextPageFromTranscriptState",
        "selectTranscriptContextPageIdsFromTranscriptState",
        "selectTranscriptEntryFromTranscriptState",
        "selectTranscriptGlobalStatusFromTranscriptState",
        "selectTranscriptTurnFragmentFromTranscriptState",
        "selectTranscriptTurnFromTranscriptState",
      ],
      "Chunk-preserving transcript read interface for the committed transcript surface.",
    ),
    publicModule(
      "transcriptState",
      "transcriptStateSlice.ts",
      [
        "TARGET_TRANSCRIPT_CHUNK_ENTRY_LIMIT",
        "TranscriptEntryId",
        "TranscriptEntryView",
        "TranscriptMessageRendering",
        "TranscriptState",
        "TranscriptTurn",
        "default",
        "selectCommittedTranscriptScrollCommitKey",
        "selectTranscriptEntry",
        "selectTranscriptLiveScrollPulse",
        "transcriptEntryIdFor",
      ],
      "Store-mounted transcript state, public view/identity contracts, chunk constraint, and committed/live scroll selectors.",
    ),
  ],
  allowedDirections: [
    // Production composition and domain consumption; these directions also allow tests.
    ...directions({ feature: "activeThreadSession" }, [
      "browserLaunch",
      "composerEditor",
      "composerInputQueue",
      "guiHost",
      "projectionIngress",
      "skillCatalog",
    ]),
    ...directions({ feature: "appShell" }, [
      "activeThreadSession",
      "browserLaunch",
      "guiHost",
      "threadRuntime",
      "transcriptState",
    ]),
    ...directions({ feature: "committedTranscriptSurface" }, ["threadRuntime", "transcriptState"]),
    ...directions({ feature: "composerEditor" }, ["composerInputQueue", "skillCatalog"]),
    ...directions({ feature: "composerInputQueue" }, [
      "activeThreadSession",
      "composerEditor",
      "guiHost",
    ]),
    ...directions({ feature: "composerTurnControl" }, [
      "activeThreadSession",
      "browserLaunch",
      "composerEditor",
      "composerInputQueue",
      "qrAccess",
      "skillCatalog",
      "threadRuntime",
    ]),
    ...directions({ feature: "currentTask" }, [
      "appShell",
      "committedTranscriptSurface",
      "composerTurnControl",
    ]),
    ...directions({ feature: "documentTitle" }, ["browserLaunch", "threadRuntime"]),
    ...directions({ feature: "qrAccess" }, ["browserLaunch"]),
    ...directions({ feature: "skillCatalog" }, ["guiHost"]),
    ...directions({ feature: "threadHistory" }, [
      "activeThreadSession",
      "appShell",
      "browserLaunch",
      "committedTranscriptSurface",
      "documentTitle",
      "guiHost",
      "qrAccess",
      "threadRuntime",
      "transcriptState",
    ]),
    ...directions({ feature: "threadRuntime" }, ["activeThreadSession"]),
    ...directions({ feature: "transcriptState" }, ["activeThreadSession", "projectionIngress"]),
    // Cross-feature fixtures and consumer integration tests do not grant production access.
    ...directions({ feature: "activeThreadSession" }, ["projection"], "testing"),
    ...directions(
      { feature: "committedTranscriptSurface" },
      ["activeThreadSession", "projection"],
      "testing",
    ),
    ...directions({ feature: "composerEditor" }, ["composerTurnControl"], "testing"),
    ...directions({ feature: "composerInputQueue" }, ["projection"], "testing"),
    ...directions({ feature: "composerTurnControl" }, ["guiHost", "projection"], "testing"),
    ...directions({ feature: "guiHost" }, ["projection"], "testing"),
    ...directions({ feature: "projectionIngress" }, ["projection"], "testing"),
    ...directions({ feature: "threadHistory" }, ["projection"], "testing"),
    ...directions({ feature: "threadRuntime" }, ["projection"], "testing"),
    ...directions({ feature: "transcriptState" }, ["projection"], "testing"),
    // Outer consumers have exact file identities, never a src/app or src/generated exemption.
    ...directions({ file: "src/App.tsx" }, [
      "activeThreadSession",
      "appShell",
      "browserLaunch",
      "guiHost",
    ]),
    ...directions({ file: "src/NotFoundPage.tsx" }, ["browserLaunch"]),
    ...directions({ file: "src/app/store.ts" }, ["threadRuntime", "transcriptState"]),
    ...directions({ file: "src/router.tsx" }, [
      "browserLaunch",
      "currentTask",
      "documentTitle",
      "threadHistory",
    ]),
    ...directions({ file: "src/routerComponents.tsx" }, ["browserLaunch"]),
    ...directions({ file: "src/generated/appServerProtocol/appServerPayloadValidators.d.ts" }, [
      "guiHost",
    ]),
    ...directions({ file: "src/generated/appServerProtocol/jsonRpcEnvelopeValidators.d.ts" }, [
      "guiHost",
    ]),
    ...directions({ file: "src/generated/appServerProtocol/requestDescriptors.ts" }, ["guiHost"]),
    ...directions({ file: "src/generated/guiHostContract/standaloneValidators.d.ts" }, ["guiHost"]),
    ...directions(
      { file: "src/__tests__/AppActiveThreadSession.browser.test.tsx" },
      [
        "activeThreadSession",
        "appShell",
        "composerInputQueue",
        "currentTask",
        "guiHost",
        "projection",
        "threadRuntime",
      ],
      "testing",
    ),
    ...directions(
      { file: "src/__tests__/AppComposerQueueInterrupt.browser.test.tsx" },
      ["composerInputQueue", "guiHost", "projection"],
      "testing",
    ),
    ...directions(
      { file: "src/__tests__/AppComposerQueueOrdinary.browser.test.tsx" },
      ["composerInputQueue", "guiHost", "projection"],
      "testing",
    ),
    ...directions(
      { file: "src/__tests__/AppComposerQueueSteer.browser.test.tsx" },
      ["composerInputQueue", "guiHost", "projection"],
      "testing",
    ),
    ...directions(
      { file: "src/__tests__/AppProjectionAvailability.browser.test.tsx" },
      ["activeThreadSession", "appShell", "guiHost", "projection", "threadRuntime"],
      "testing",
    ),
    ...directions(
      { file: "src/__tests__/AppProjectionIngress.browser.test.tsx" },
      [
        "activeThreadSession",
        "appShell",
        "composerInputQueue",
        "guiHost",
        "projection",
        "threadRuntime",
      ],
      "testing",
    ),
    ...directions(
      { file: "src/__tests__/AppProjectionScroll.browser.test.tsx" },
      ["guiHost", "projection", "threadRuntime", "transcriptState"],
      "testing",
    ),
    ...directions(
      { file: "src/__tests__/AppRouting.browser.test.tsx" },
      ["activeThreadSession", "browserLaunch", "guiHost", "projection"],
      "testing",
    ),
    ...directions(
      { file: "src/__tests__/AppSessionCompaction.browser.test.tsx" },
      ["guiHost", "projection"],
      "testing",
    ),
    ...directions(
      { file: "src/__tests__/AppShell.browser.test.tsx" },
      [
        "activeThreadSession",
        "appShell",
        "composerInputQueue",
        "currentTask",
        "guiHost",
        "projection",
        "threadRuntime",
      ],
      "testing",
    ),
    ...directions(
      { file: "src/__tests__/NotFoundPage.browser.test.tsx" },
      ["currentTask", "guiHost", "threadHistory"],
      "testing",
    ),
    ...directions(
      { file: "src/__tests__/appBrowserRenderHarness.tsx" },
      ["browserLaunch", "currentTask", "threadHistory"],
      "testing",
    ),
    ...directions(
      { file: "src/__tests__/appBrowserTestSupport.ts" },
      ["browserLaunch", "guiHost", "projection"],
      "testing",
    ),
    ...directions(
      { file: "src/__tests__/appComposerQueueBrowserTestSupport.tsx" },
      ["composerInputQueue", "guiHost", "projection"],
      "testing",
    ),
    ...directions(
      { file: "src/__tests__/sequential/composer-viewport.browser.test.tsx" },
      [
        "activeThreadSession",
        "composerInputQueue",
        "composerTurnControl",
        "guiHost",
        "projection",
        "skillCatalog",
      ],
      "testing",
    ),
    ...directions(
      { file: "src/__tests__/sequential/composerClipboard.browser.test.tsx" },
      ["composerEditor", "skillCatalog"],
      "testing",
    ),
    ...directions(
      { file: "src/__tests__/sequential/subagent-activity-responsive.browser.test.tsx" },
      ["activeThreadSession", "committedTranscriptSurface", "projection"],
      "testing",
    ),
    ...directions(
      { file: "src/__tests__/smoke/AppComposerQueue.smoke.browser.test.tsx" },
      ["composerInputQueue", "guiHost", "projection", "transcriptState"],
      "testing",
    ),
    ...directions(
      { file: "src/__tests__/smoke/AppRouting.smoke.browser.test.tsx" },
      ["activeThreadSession", "guiHost"],
      "testing",
    ),
    ...directions(
      { file: "src/__tests__/smoke/AppThreadSwitch.smoke.browser.test.tsx" },
      [
        "activeThreadSession",
        "appShell",
        "composerInputQueue",
        "guiHost",
        "projection",
        "threadRuntime",
        "transcriptState",
      ],
      "testing",
    ),
  ],
  testSupportFiles: ["src/utils/TestProvider.tsx", "src/utils/test-utils.tsx"],
  knownDirectionIssues: [
    {
      from: "composerEditor",
      to: "composerInputQueue",
      issue:
        "../docs/superpowers/issues/2026/09/04/2026-09-04-01-codex-gui-shared-infrastructure-problems/2026-09-04-03-composer-draft-input-contract-direction.md",
      description:
        "Editor capture uses the queue-owned readonly payload contract; no draft/input owner migration is included.",
    },
    {
      from: "composerInputQueue",
      to: "composerEditor",
      issue:
        "../docs/superpowers/issues/2026/09/04/2026-09-04-01-codex-gui-shared-infrastructure-problems/2026-09-04-03-composer-draft-input-contract-direction.md",
      description:
        "Queue retains opaque editor drafts and captures plus restoration outcomes; this necessary reverse contract remains explicitly unresolved.",
    },
  ],
};
