// GENERATED CODE! DO NOT MODIFY BY HAND!

export const THREAD_QUERY_KEY = "threadId" as const;
export const TOKEN_FRAGMENT_KEY = "token" as const;
export const WEBSOCKET_PATH = "/ws" as const;
export const AUTHENTICATE_METHOD = "gui/authenticate" as const;

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GuiAuthenticateParams = { token: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GuiAuthenticateResult = { authenticated: boolean, };
