// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JSONRPCError } from "./JSONRPCError";
import type { JSONRPCNotification } from "./JSONRPCNotification";
import type { JSONRPCRequest } from "./JSONRPCRequest";
import type { JSONRPCResponse } from "./JSONRPCResponse";

/**
 * Refers to any valid JSON-RPC object that can be decoded off the wire, or encoded to be sent.
 */
export type JSONRPCMessage = JSONRPCRequest | JSONRPCNotification | JSONRPCResponse | JSONRPCError;
