// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JSONRPCErrorError } from "./JSONRPCErrorError";
import type { RequestId } from "./RequestId";

/**
 * A response to a request that indicates an error occurred.
 */
export type JSONRPCError = { error: JSONRPCErrorError, id: RequestId, };
