// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestId } from "./RequestId";
import type { W3cTraceContext } from "./W3cTraceContext";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A request that expects a response.
 */
export type JSONRPCRequest = { id: RequestId, method: string, params?: JsonValue,
/**
 * Optional W3C Trace Context for distributed tracing.
 */
trace?: W3cTraceContext, };
